package ifc;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.Sleeper;

import java.time.Duration;
import java.util.*;

public class SeleniumExecutor {

    private WebDriver driver;
    private Map<String, Object> vars;
    private List<String> buttons = new ArrayList<>();
    JavascriptExecutor js;

    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        buttons.addAll(Arrays.asList(".inline-btn:nth-child(2)",
                ".inline-btn:nth-child(3)",
                ".inline-btn:nth-child(4)",
                ".inline-btn:nth-child(5)",
                ".inline-btn:nth-child(6)",
                ".inline-btn:nth-child(7)"));
    }

    public void run(Main.Credentials credentials) throws InterruptedException {
        this.setUp();
        driver.get("http://localhost:3000/login");
        driver.manage().window().maximize();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys(credentials.getUser());
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys(credentials.getPassword());
        driver.findElement(By.cssSelector(".btn")).click();
        {
            WebElement element = driver.findElement(By.linkText("Entrar"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.linkText("Entrar")).click();
        while (!driver.findElement(By.cssSelector("#current-time")).getText().equals("00:01")) {
            System.out.println(driver.findElement(By.cssSelector("#current-time")).getText());
            Sleeper.SYSTEM_SLEEPER.sleep(Duration.ofSeconds(3));
            driver.findElement(By.cssSelector(buttons.get(new Random().nextInt(buttons.size())))).click();
        }
        driver.quit();
    }
}